--RUN SCRIPT
DROP TABLE STAYIN;
DROP TABLE ROOMSERVICE;
DROP TABLE ROOMACCESS;
DROP TABLE EXAMINE;
DROP TABLE ADMISSION;
DROP TABLE CANREPAIREQUIPMENT;
DROP TABLE EQUIPMENTTECHNICIAN;
DROP TABLE EQUIPMENT;
DROP TABLE EQUIPMENTTYPE;
DROP TABLE ROOM;
DROP TABLE PATIENT;
DROP TABLE DOCTOR;
DROP TABLE EMPLOYEE;

@CreateTables.sql
@InitializeDataset.sql
@Queries.sql